### ISSUE TITLE
how to get v2 cli?

### ISSUE THREAD

**Issue by mark-hahn** [guessit-io/guessit#240]
I'm still getting 1.0.2 when I do `pip install --upgrade guessit`.  How can I upgrade to v2?

I want to upgrade because I have some bad guess examples and I want to make sure I don't report something that is fixed in v2.

**Comment by Toilal** [comment]
Use --pre flag with pip. It doesn't go to 2.0 automatically because it's
still a release candidate, but I think it will be released in the next few
days as stable.

**Comment by mark-hahn** [comment]
thanks

**Comment by mark-hahn** [comment]
I'm getting an install error with `pip install --pre guessit` and `python setup.py install` in the repo.  Both have the same error.  The stderr output and the log file are included below.  Installing V1 still works.

I'm using Python 2.7.3 on Ubuntu 12.04.5.  How should I proceed?

```
pip install --pre guessit
Downloading/unpacking guessit
  Downloading guessit-2.0rc4.tar.gz (69kB): 69kB downloaded
  Running setup.py (path:/tmp/pip_build_root/guessit/setup.py) egg_info for package guessit
    
    Installed /tmp/easy_install-329Otd/pytest-runner-2.6.2/setuptools_scm-1.10.0-py2.7.egg
    your setuptools is too old (<12)
    setuptools_scm functionality is degraded
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip_build_root/guessit/pytest_runner-2.6.2-py2.7.egg
    
    warning: no files found matching '*.ini' under directory 'guessit'
    warning: no previously-included files matching '*.pyc' found under directory 'guessit'
Requirement already satisfied (use --upgrade to upgrade): rebulk>=0.6.4 in /usr/local/lib/python2.7/dist-packages (from guessit)
Downloading/unpacking regex (from guessit)
  Downloading regex-2015.11.22.tar.gz (574kB): 574kB downloaded
  Running setup.py (path:/tmp/pip_build_root/regex/setup.py) egg_info for package regex
    
Requirement already satisfied (use --upgrade to upgrade): babelfish>=0.5.5 in /usr/local/lib/python2.7/dist-packages (from guessit)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/lib/python2.7/dist-packages (from guessit)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from rebulk>=0.6.4->guessit)
Installing collected packages: guessit, regex
  Running setup.py install for guessit
    
    warning: no files found matching '*.ini' under directory 'guessit'
    warning: no previously-included files matching '*.pyc' found under directory 'guessit'
    Installing guessit script to /usr/local/bin
  Running setup.py install for regex
    building '_regex' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c Python2/_regex.c -o build/temp.linux-x86_64-2.7/Python2/_regex.o
    Python2/_regex.c:46:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/regex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-p1vfkv-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

copying Python2/regex.py -> build/lib.linux-x86_64-2.7

copying Python2/_regex_core.py -> build/lib.linux-x86_64-2.7

copying Python2/test_regex.py -> build/lib.linux-x86_64-2.7

running build_ext

building '_regex' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/Python2

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c Python2/_regex.c -o build/temp.linux-x86_64-2.7/Python2/_regex.o

Python2/_regex.c:46:20: fatal error: Python.h: No such file or directory

 #include "Python.h"

                    ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/regex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-p1vfkv-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/regex
Storing debug log for failure in /root/.pip/pip.log
```

Contents of  /root/.pip/pip.log ...

```
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/regex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-p1vfkv-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

copying Python2/regex.py -> build/lib.linux-x86_64-2.7

copying Python2/_regex_core.py -> build/lib.linux-x86_64-2.7

copying Python2/test_regex.py -> build/lib.linux-x86_64-2.7

running build_ext

building '_regex' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/Python2

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c Python2/_regex.c -o build/temp.linux-x86_64-2.7/Python2/_regex.o

Python2/_regex.c:46:20: fatal error: Python.h: No such file or directory

 #include "Python.h"

                    ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

--- <cleaning up snipped> ...
```

**Comment by Toilal** [comment]
You need python headers files to get this [regex](https://pypi.python.org/pypi/regex) module compiled.

I'll assume something like `apt-get install python-dev` should work.

**Comment by mark-hahn** [comment]
That did it.  The new version has fixed the bad guess I was going to report so things are great for now.

Thanks.

**Comment by Toilal** [comment]
Only for information, could you tell me the use case that was fixed with the rewrite of guessit 2 ?

**Comment by mark-hahn** [comment]
I don't think I still have a copy of it.  If it is important I can load v1
and run my files again.

If I remember correctly it had something to do with dashes surrounded by
white space.  I could be wrong.
